version: "3.7"

services:
  api:
    container_name: fact-back
    image: python
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mongo
    volumes:
      - .:/api
    env_file:
      - .env.local
    environment:
      - PORT=5050

  mongo:
    container_name: mongo-db
    image: mongo
    volumes:
      - "./db:/data/db"

